#!/bin/bash

if [[ -z "$@" ]]; then
	options=(
		lenny
		boat
		bbye
		void
		pyig
		reverse
		small
		i18n
		"float term"
		google
		youtube
		lichess
		weeb
	)
	formatted=$(printf "%s\n" "${options[@]}")
	echo "$formatted"
else
	case "$@" in
		"lenny")
			coproc ( echo -n "( ͡° ͜ʖ ͡°)" | xclip -selection c )
			exit
			;;
		"boat")
			coproc ( echo -n '( . \_\_\_\_\_.)' | xclip -selection c )
			exit
			;;
		"bbye")
			coproc ( echo -n ":b:bye, my guy" | xclip -selection c )
			exit
			;;
		"void")
			coproc ( ~/Scripts/void.py | xclip -selection c )
			exit
			;;
		"pyig")
			coproc ( xclip -o | ~/Scripts/pyig_latin.py | xclip -selection c )
			exit
			;;
		"reverse")
			coproc ( xclip -o | rev | xclip -selection c )
			exit
			;;
		"small")
			coproc ( xclip -o | ~/Scripts/small_text.py | xclip -selection c )
			exit
			;;
		"i18n")
			coproc ( xclip -o | ~/Scripts/i18n.py | xclip -selection c )
			exit
			;;
		"float term")
			coproc ( coproc ( alacritty ); sleep 0.25; i3-msg "floating toggle; [floating] border pixel 10; [tiling] border normal 3" )
			exit
			;;
		"google")
			coproc ( coproc ( firefox -new-tab www.google.com ) )
			exit
			;;
		"youtube")
			coproc ( coproc ( firefox -new-tab www.youtube.com ) )
			exit
			;;
		"lichess")
			coproc ( coproc ( chromium --app=https://www.lichess.org/ ) )
			exit
			;;
		"weeb")
			coproc ( xclip -o | ~/Scripts/to_jp.py | xclip -selection c )
			exit
			;;
		*)
			exit
			;;
	esac
fi
