#!/bin/bash

setxkbmap -query | grep "variant" > /dev/null
if [ $? -gt 0 ]; then
	echo "Setting to international keybaord"
	setxkbmap us -variant intl
else
	echo "Setting to default keyboard"
	setxkbmap us
fi
