#!/bin/bash

setxkbmap -query | grep "variant" > /dev/null
if [ $? -gt 0 ]; then
	notify-send "Keyboard Variant Change" "Changed to international layout"
	setxkbmap us -variant intl
else
	notify-send "Keyboard Variant Change" "Changed to standard layout"
	setxkbmap us
fi
